// <auto-generated />
using System;
using Audit.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Audit.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("audit")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Audit.Domain.Aggregates.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousHash")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.HasIndex("TenantId", "Timestamp");

                    b.ToTable("audit_entries", "audit");
                });

            modelBuilder.Entity("Audit.Infrastructure.Persistence.Configurations.AuditConsumedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("audit_consumed_events", "audit");
                });

            modelBuilder.Entity("BuildingBlocks.Kernel.Domain.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOn");

                    b.ToTable("OutboxMessages", "audit");
                });

            modelBuilder.Entity("Audit.Domain.Aggregates.AuditEntry", b =>
                {
                    b.OwnsOne("Audit.Domain.ValueObjects.ActorReference", "Actor", b1 =>
                        {
                            b1.Property<Guid>("AuditEntryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uuid")
                                .HasColumnName("ActorId");

                            b1.Property<string>("ActorType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ActorType");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ActorDisplayName");

                            b1.HasKey("AuditEntryId");

                            b1.ToTable("audit_entries", "audit");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId");
                        });

                    b.OwnsOne("Audit.Domain.ValueObjects.AuditResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("AuditEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ErrorCode")
                                .HasColumnType("text")
                                .HasColumnName("ErrorCode");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Result");

                            b1.HasKey("AuditEntryId");

                            b1.ToTable("audit_entries", "audit");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId");
                        });

                    b.OwnsOne("Audit.Domain.ValueObjects.BeforeAfterSnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("AuditEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AfterJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("AfterJson");

                            b1.Property<string>("BeforeJson")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("BeforeJson");

                            b1.HasKey("AuditEntryId");

                            b1.ToTable("audit_entries", "audit");

                            b1.WithOwner()
                                .HasForeignKey("AuditEntryId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();

                    b.Navigation("Result")
                        .IsRequired();

                    b.Navigation("Snapshot")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
