<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Projects\Projects.Domain\Projects.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Projects\Projects.Infrastructure\Projects.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Projects\Projects.Application\Projects.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Projects\Projects.Contracts\Projects.Contracts.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\BuildingBlocks.Kernel.Domain\BuildingBlocks.Kernel.Domain.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\BuildingBlocks.CQRS\BuildingBlocks.CQRS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>